// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKeRWdUzCvVxUJIOuBbEr2W7PcVftTWag',
    appId: '1:888093115648:web:7a5ea3cf42fb8809375fe5',
    messagingSenderId: '888093115648',
    projectId: 'chat-app-project-2c2fc',
    authDomain: 'chat-app-project-2c2fc.firebaseapp.com',
    storageBucket: 'chat-app-project-2c2fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjHLst9QdFKx55jAcQha3DfPbn-pRYeeM',
    appId: '1:888093115648:android:eaf1d2b86cb5b479375fe5',
    messagingSenderId: '888093115648',
    projectId: 'chat-app-project-2c2fc',
    storageBucket: 'chat-app-project-2c2fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5UH6cC_DF-OwA04ZLMnFV7GWdmjgf1yA',
    appId: '1:888093115648:ios:40e4be41ebbdd78a375fe5',
    messagingSenderId: '888093115648',
    projectId: 'chat-app-project-2c2fc',
    storageBucket: 'chat-app-project-2c2fc.appspot.com',
    iosBundleId: 'com.example.chatAppBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5UH6cC_DF-OwA04ZLMnFV7GWdmjgf1yA',
    appId: '1:888093115648:ios:83d1a8a346dc9dcd375fe5',
    messagingSenderId: '888093115648',
    projectId: 'chat-app-project-2c2fc',
    storageBucket: 'chat-app-project-2c2fc.appspot.com',
    iosBundleId: 'com.example.chatAppBox.RunnerTests',
  );
}
